# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GitHub CI (Latest v1.1)

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: 'Tag'
    #     required: true
    #     default: 'latest-1.1'
  schedule:
    - cron: "0 */4 * * *"

env:
  tag: "latest-1.1"

jobs:
  build:
    runs-on: ubuntu-latest
    # continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        framework:
          - angular
          - angularjs
#           - aurelia
          - inferno
          - lit-element
          - preact
          - react
#           - solid
          - svelte
          - vanilla
          - vue
          - vue3
    name: Test "${{matrix.framework}}" framework
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
      - name: Test "${{matrix.framework}}" framework
        shell: bash
        run: |
          cp -r public dist
          bash ./wake-up.sh ${{matrix.framework}} ${{env.tag}}
      - name: Separate build run
        run: npm run build
        working-directory: workspace
      - name: List build artifacts
        run: |
          ls -la dist/
          mkdir ${{env.tag}}
          mv dist/* ${{env.tag}}/
          mv ${{env.tag}} dist/
          ls -la dist/${{env.tag}}/
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          known-hosts: ${{ secrets.FTP_KNOWN_HOSTS }}
          local-dir: dist/
          git-ftp-args: --all
